baseurl = "http://jackmordaunt.com/"
title = "Jack Mordaunt"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Jack Mordaunt"
  info = "Coffee developer, software brewer."
  description = "Coffee developer, software brewer."
  keywords = "blog,developer,personal,software,robust,performance,sovereign"
  avatarurl = "images/self.jpg"
  gravatar = "gravatar@sovereignlife.anonaddy.com"

  faviconSVG = "/images/self-tiny-white.svg"
  favicon_32 = "/images/self-tiny-white.png"
  favicon_16 = "/images/self-tiny-white.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
  #

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jackmordaunt"
[[params.social]]
  name = "Sourcehut"
  icon = "fa-1x"
  svg = "assets/images/sourcehut.svg"
  weight = 2
  url = "https://git.sr.ht/~jackmordaunt"
[[params.social]]
  name = "Public Keys"
  icon = "fa-solid fa-key fa-2x"
  weight = 3
  url = "https://meta.sr.ht/~jackmordaunt.pgp"
[[params.social]]
  name = "Bitcoin"
  icon = "fa-brands fa-bitcoin fa-2x"
  weight = 4
  url = "pay-with-bitcoin/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Contact"
  weight = 3
  url = "contact/"
[[menu.main]]
  name = "Pay"
  weight = 4
  url = "pay-with-bitcoin/"
